version: "3.8"
services:
  web:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    networks:
      - proxynet
      - appnet
    labels:
      - "traefik.http.routers.xsolutions.rule=(Host(`projectx.localhost`))"
      - "traefik.http.routers.xsolutions-https.rule=(Host(`projectx.localhost`))"
      - "traefik.http.routers.xsolutions-https.entrypoints=https"
      - "traefik.http.routers.xsolutions-https.tls=true"
      - "traefik.http.routers.xsolutions-https.tls.domains[0].main=projectx.localhost"
      - "traefik.docker.network=proxy-net"
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: xsolutions/projectx-app:latest
    volumes:
      - .:/var/www/html
    networks:
      - appnet
      - mysqlnet
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - appnet
      - mysqlnet
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: projectx
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: projectx
    ports:
      - 27019:27017
    networks:
      - appnet
    volumes:
      - mongodata:/data/db
  redis:
    image: redis:alpine
    networks:
      - appnet
  testdb:
    image: mysql:5.7
    ports:
      - "33065:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: projectx_test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - appnet
    volumes:
      - testdb:/var/lib/mysql
networks:
  appnet:
    driver: bridge
  proxynet:
    external: true
    name: proxy-net
  mysqlnet:
    external: true
    name: mysql-net
volumes:
  testdb:
    driver: local
  mongodata:
    driver: local
